language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install
script:
  - ./run_specs.sh
notifications:
  email: false
